<a href="https://colab.research.google.com/github/parthsarthi1052/Data-Science/blob/main/Data4(numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [6]:
# import numpy as np
a=np.array([1,3,4,2,0,8,'2'])
print(a)

['1' '3' '4' '2' '0' '8' '2']


In [12]:
np_arr=np.array([3,3,3,3,3.3,'hello',False])
print(bool(np_arr[-1]))

a=False
print(bool(a))

True
False


In [20]:
a=np.zeros((2,3,3),dtype=int)
print(a)
print(type(a[0][0][0]))

<class 'numpy.int64'>


In [21]:
a=np.ones((2,3,3),dtype=int)
print(a)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [26]:
a=np.empty(9,dtype=int)
print(a)

[     1074659371               0        11700632 132350512872528
               0               0               0               0
               0]


In [28]:
a=np.full(4,5,dtype=int)
print(a)

[5 5 5 5]


In [45]:
a=np.arange(3,dtype=int)
print(a)

[0 1 2]


In [46]:
a=np.linspace(2,3,4,dtype=int)
print(a)

[2 2 2 3]


In [53]:
a=np.full(4,7,dtype=int)
print(a)
print(a.size)
print(a.shape)
print(a.ndim)
print(a.dtype)

[7 7 7 7]
4
(4,)
1
int64


In [58]:
a=np.random.randint(10,30,5)
print(a)

b=np.random.choice([1,5,3,2],3)
print(b)

[12 12 15 12 25]
[3 3 2]


In [64]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(a+b)
print(a*2)
print(a*b)
print(a%b)
print(a+2*b)

[ 7  9 11 13 15]
[ 2  4  6  8 10]
[ 6 14 24 36 50]
[1 2 3 4 5]
[13 16 19 22 25]


In [68]:
lst=[1,2,3,4,5]
lst1=[6,7,8,9,10]
print(lst+lst1)
# print(2*lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [78]:
ls=[10,20,30]
l=[20,70,40]
import numpy as np
a=np.random.randint(2,7,6)
print(a)
print(ls+l)
print(2*ls)
x=a.reshape(2,3)
y=a.reshape(2,3)
print(x)
print(x.transpose())
# print(concatenate(x,y))


[4 5 6 3 4 4]
[10, 20, 30, 20, 70, 40]
[10, 20, 30, 10, 20, 30]
[[4 5 6]
 [3 4 4]]
[[4 3]
 [5 4]
 [6 4]]


In [95]:
a=np.random.randint(2,15,6)
b=np.random.randint(2,19,6)

x=a.reshape(2,3)
y=b.reshape(2,3)


print(x)
print(y)
print(np.concatenate((x,y),axis=1))

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [89]:
a=np.random.randint(2,15,6)
b=np.random.randint(2,19,6)

print(a)
print(b)

c=np.where(b>2,b,a)
print(c)

[11 13  9  6  3 12]
[ 2 11  9  9  8 11]
[11 11  9  9  8 11]


In [97]:
a=np.random.randint(2,15,6)
b=np.random.randint(2,19,6)

print(a)
c=np.sort(a)
print(c)

print(np.sum(a))
print(np.mean(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))
print(np.unique(a))

print(np.matmul(a,b))



[6 8 4 8 3 4]
[3 4 4 6 8 8]
33
5.5
1.9790570145063195
3
8
[3 4 6 8]
393


In [105]:
lst=input("Weekly Scores:").split()

a=np.array([lst],dtype=int)


print(a)
print("Sum is:",np.sum(a))
print("Mean is:",np.mean(a))
print("Deviation is:",np.std(a))
print("Min Score is:",np.min(a))
print("Max Score is:",np.max(a))

Weekly Scores10 20 30 40 50 60 70
[[10 20 30 40 50 60 70]]
Sum is: 280
Mean is: 40.0
Deviation is: 20.0
Min Score is: 10
Max Score is: 70
