<a href="https://colab.research.google.com/github/parthsarthi1052/Data-Science/blob/main/Data_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Ques-1
import numpy as np
a=np.random.randint(1,90,25)
x=a.reshape(5,5)
print(x)
print("\n")
# mean
print(np.mean(a))
print(np.mean(x))
print(np.mean(x,axis=0))#columnwise
print(np.mean(x,axis=1))#row-wise
print("\n")
# sum
b=np.sum(x,axis=0)
print(b)
c=np.sum(x,axis=1)
print(c)
print("\n")
# sort
d=np.sort(x,axis=1)
print(d)
print("\n")
e=np.sort(x,axis=0)
print(e)
print("\n")
#replace
for i in range(0,25):
  if(a[i]%2==0):
    a[i]=-1
y=a.reshape(5,5)
print(y)
#count
count_col=np.sum(np.where(y<0,1,0),axis=0)
print(count_col)




[[17 63 14 42 26]
 [49 69 77  4 19]
 [89 12 76 21 14]
 [29 54 54 12 89]
 [56 78 24 13 81]]


43.28
43.28
[48.  55.2 49.  18.4 45.8]
[32.4 43.6 42.4 47.6 50.4]


[240 276 245  92 229]
[162 218 212 238 252]


[[14 17 26 42 63]
 [ 4 19 49 69 77]
 [12 14 21 76 89]
 [12 29 54 54 89]
 [13 24 56 78 81]]


[[17 12 14  4 14]
 [29 54 24 12 19]
 [49 63 54 13 26]
 [56 69 76 21 81]
 [89 78 77 42 89]]


[[17 63 -1 -1 -1]
 [49 69 77 -1 19]
 [89 -1 -1 21 -1]
 [29 -1 -1 -1 89]
 [-1 -1 -1 13 81]]
[1 3 4 3 2]


In [ ]:
# Ques-2
import numpy as np
a=np.random.randint(20,80,25)
b=np.random.randint(20,80,25)

stock=a.reshape(5,5)
demand=b.reshape(5,5)
# remaining stock
rstock=stock-demand
print(rstock)
# total shortage
totalShortage = np.sum(np.where(rstock<0,-1*rstock,0),axis = 0)
print("\nTotal Shortage : \n",totalShortage)
# replace zero
mr=np.where(rstock<0,0,rstock)
print(mr)
# zero stock
zero=np.sum(np.where(mr==0,1,0),axis=0)
print(zero)
# row sort
mrp=np.sort(mr,axis=1)
print(mrp)

[[ 29  10 -49  42 -34]
 [-46  50  25   9  38]
 [ -4  -8 -42   9   8]
 [ 18 -26   4  13   9]
 [ -2 -17  -7  42  42]]

Total Shortage : 
 [52 51 98  0 34]
[[29 10  0 42  0]
 [ 0 50 25  9 38]
 [ 0  0  0  9  8]
 [18  0  4 13  9]
 [ 0  0  0 42 42]]
[3 3 3 0 1]
[[ 0  0 10 29 42]
 [ 0  9 25 38 50]
 [ 0  0  0  8  9]
 [ 0  4  9 13 18]
 [ 0  0  0 42 42]]


In [14]:
# Pandas
import pandas as pd
file=pd.read_csv("./student_data.csv")
# print(file);
print("\n")
pd.DataFrame(file)
print(file.head(9))
print(file.tail(10))



   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7   
1            4          69            5               3   
2           11          60            7               6   
3            8          99            9               8   
4            5          52            8               6   
5            7          40            9              10   
6           10          40            4              11   
7            3          86            7               3   
8            7          72            8               5   

   assignments_completed  previous_score  exam_score placement_status  
0                     10              62      100.00           Placed  
1                      8              56      100.00           Placed  
2                     10              45      100.00           Placed  
3                      4              55       90.17           Placed  
4                      8              40       

In [ ]:
from google.colab import drive

